// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: proto/course_category.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CategorySeviceClient is the client API for CategorySevice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategorySeviceClient interface {
	CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error)
}

type categorySeviceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategorySeviceClient(cc grpc.ClientConnInterface) CategorySeviceClient {
	return &categorySeviceClient{cc}
}

func (c *categorySeviceClient) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error) {
	out := new(CategoryResponse)
	err := c.cc.Invoke(ctx, "/pb.CategorySevice/CreateCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategorySeviceServer is the server API for CategorySevice service.
// All implementations must embed UnimplementedCategorySeviceServer
// for forward compatibility
type CategorySeviceServer interface {
	CreateCategory(context.Context, *CreateCategoryRequest) (*CategoryResponse, error)
	mustEmbedUnimplementedCategorySeviceServer()
}

// UnimplementedCategorySeviceServer must be embedded to have forward compatible implementations.
type UnimplementedCategorySeviceServer struct {
}

func (UnimplementedCategorySeviceServer) CreateCategory(context.Context, *CreateCategoryRequest) (*CategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedCategorySeviceServer) mustEmbedUnimplementedCategorySeviceServer() {}

// UnsafeCategorySeviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategorySeviceServer will
// result in compilation errors.
type UnsafeCategorySeviceServer interface {
	mustEmbedUnimplementedCategorySeviceServer()
}

func RegisterCategorySeviceServer(s grpc.ServiceRegistrar, srv CategorySeviceServer) {
	s.RegisterService(&CategorySevice_ServiceDesc, srv)
}

func _CategorySevice_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategorySeviceServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CategorySevice/CreateCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategorySeviceServer).CreateCategory(ctx, req.(*CreateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CategorySevice_ServiceDesc is the grpc.ServiceDesc for CategorySevice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategorySevice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CategorySevice",
	HandlerType: (*CategorySeviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCategory",
			Handler:    _CategorySevice_CreateCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/course_category.proto",
}
