POST http://localhost:8000/user HTTP/1.1
Content-Type: application/json

{
    "name": "Zé",
    "email": "z@mail.com",
    "password": "567890"
}

###

POST http://localhost:8000/user/gen_token HTTP/1.1
Content-Type: application/json

{
    "email": "z@mail.com",
    "password": "567890"
}

