// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: queries.sql

package db

import (
	"context"
)

const createCategory = `-- name: CreateCategory :exec
INSERT INTO categories(id, name) VALUES (?,?)
`

type CreateCategoryParams struct {
	ID   int32
	Name string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createCategory, arg.ID, arg.Name)
	return err
}

const createCourses = `-- name: CreateCourses :exec
INSERT INTO courses (id, name, category_id) VALUES (?, ?, ?)
`

type CreateCoursesParams struct {
	ID         int32
	Name       string
	CategoryID int32
}

func (q *Queries) CreateCourses(ctx context.Context, arg CreateCoursesParams) error {
	_, err := q.db.ExecContext(ctx, createCourses, arg.ID, arg.Name, arg.CategoryID)
	return err
}
